#!/usr/bin/python3
import sys

arg = sys.argv
f = open("r", arg[2])
for line in f:
    number = line
    for i in range(2, number + 1):
        if (number % i == 0):
            print("{0}={1}*{2}".format(number, number/i, i))
