#!/usr/bin/python3
import sys

arg = sys.argv
f = open(arg[-1], 'r')
for line in f:
    number = int(line)
    if (number % 2 == 0):
        print("{}={}*{}".format(number, number//2, 2))
    else:
        i = 3
        while (i < number):
            if (number % i == 0):
                print("{}={}*{}".format(number, number//i, i))
                break
            i += 2
f.close()
